services:

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - sih-network

  ml-service1:
    build:
      context: ./ml-service1
    container_name: sih-ml-service1-container
    ports:
      - "8000:8000"
    networks:
      - sih-network

  backend:
    build: ./backend
    container_name: sih-backend-container
    env_file:
      - ./backend/.env
    environment:
      ML_SERVICE_URL: http://ml-service1:8000
      MQTT_BROKER: mqtt-broker
    depends_on:
      - mqtt-broker
      - ml-service1
    networks:
      - sih-network

  simulator:
    build: ./simulator
    container_name: sih-simulator-container
    env_file:
      - ./simulator/.env
    environment:
      MQTT_BROKER: mqtt-broker
    depends_on:
      - mqtt-broker
    networks:
      - sih-network

  prometheus:
    image: prom/prometheus
    container_name: sih-prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend
    networks:
      - sih-network
  
  grafana:
    image: grafana/grafana
    container_name: sih-grafana-container
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - sih-network

networks:
  sih-network:
    driver: bridge
