export const ROLES = Object.freeze({
  ADMIN: "admin",
  ENGINEER: "engineer",
  OPERATOR: "operator",
});

export const PERMISSIONS = Object.freeze({
  DASHBOARD_READ: "dashboard:read",
  SENSORS_READ: "sensors:read",
  SENSORS_CONFIGURE: "sensors:configure",

  STATIONS_READ: "stations:read",
  STATIONS_CREATE: "stations:create",
  STATIONS_UPDATE: "stations:update",
  STATIONS_DELETE: "stations:delete",
  STATIONS_ASSIGN: "stations:assign",

  HISTORY_READ: "history:read",
  ANOMALIES_READ: "anomalies:read",

  ALERTS_READ: "alerts:read",
  ALERTS_ACKNOWLEDGE: "alerts:acknowledge",
  ALERTS_RESOLVE: "alerts:resolve",

  MAINTENANCE_READ: "maintenance:read",
  MAINTENANCE_CREATE: "maintenance:create",
  MAINTENANCE_UPDATE: "maintenance:update",

  TASK_CREATE: "task:create",
  TASK_READ: "task:read",
  TASK_READ_ALL: "task:read_all",
  TASK_ASSIGN: "task:assign",
  TASK_UPDATE: "task:update",
  TASK_COMPLETE: "task:complete",

  USERS_READ: "users:read",
  USERS_CREATE: "users:create",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  ROLES_MANAGE: "roles:manage",
  USERS_MANAGE_STATUS: "users:manage_status",
  USER_APPROVE: "users:approve",
  USER_REJECT: "users:reject",

  NOTIFICATION_READ: "notifications:read",

  AUDIT_READ: "audit:read",
  METRICS_READ: "metrics:read",
  SIMULATION_RUN: "simulation:run",
  SYSTEM_CONFIGURE: "system:configure",
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.SENSORS_READ,
    PERMISSIONS.SENSORS_CONFIGURE,
    PERMISSIONS.STATIONS_READ,
    PERMISSIONS.STATIONS_CREATE,
    PERMISSIONS.STATIONS_UPDATE,
    PERMISSIONS.STATIONS_DELETE,
    PERMISSIONS.STATIONS_ASSIGN,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.ANOMALIES_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.ALERTS_RESOLVE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_READ_ALL,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.USERS_MANAGE_STATUS,
    PERMISSIONS.USER_APPROVE,
    PERMISSIONS.USER_REJECT,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.METRICS_READ,
    PERMISSIONS.SIMULATION_RUN,
    PERMISSIONS.SYSTEM_CONFIGURE,
  ],

  [ROLES.OPERATOR]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.SENSORS_READ,
    PERMISSIONS.STATIONS_READ,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.ANOMALIES_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.ALERTS_RESOLVE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.NOTIFICATION_READ,
  ],

  [ROLES.ENGINEER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.SENSORS_READ,
    PERMISSIONS.STATIONS_READ,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.ANOMALIES_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.NOTIFICATION_READ,
  ],
});

export function getPermissionsForRole(role) {
  if (!role) return [];
  const normalized = String(role).toLowerCase().trim();
  return ROLE_PERMISSIONS[normalized] || [];
}

export function hasPermission(role, permission) {
  const permissions = getPermissionsForRole(role);
  return permissions.includes(permission);
}

export function isValidRole(role) {
  if (!role) return false;
  return Object.values(ROLES).includes(String(role).toLowerCase().trim());
}
